# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AspectRatio',
            fields=[
                ('aspect_ratio_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('prefix', models.CharField(max_length=2)),
                ('width_units', models.IntegerField()),
                ('height_units', models.IntegerField()),
            ],
            options={
                'db_table': 'aspect_ratio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('display_order', models.IntegerField()),
                ('ts_ls_x', models.TextField(blank=True, null=True)),
                ('ts_ls_w', models.TextField(blank=True, null=True)),
                ('ts_ls_y', models.TextField(blank=True, null=True)),
                ('ts_ls_h', models.TextField(blank=True, null=True)),
                ('ts_pt_x', models.TextField(blank=True, null=True)),
                ('ts_pt_w', models.TextField(blank=True, null=True)),
                ('ts_pt_y', models.TextField(blank=True, null=True)),
                ('ts_pt_h', models.TextField(blank=True, null=True)),
                ('ns_ls_x', models.TextField(blank=True, null=True)),
                ('ns_ls_w', models.TextField(blank=True, null=True)),
                ('ns_ls_y', models.TextField(blank=True, null=True)),
                ('ns_ls_h', models.TextField(blank=True, null=True)),
                ('ns_pt_x', models.TextField(blank=True, null=True)),
                ('ns_pt_w', models.TextField(blank=True, null=True)),
                ('ns_pt_y', models.TextField(blank=True, null=True)),
                ('ns_pt_h', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CardTargetDevice',
            fields=[
                ('card_target_device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ls_xcasset_name', models.CharField(max_length=20)),
                ('pt_xcasset_name', models.CharField(max_length=20)),
                ('ls_crop_x', models.TextField(blank=True, null=True)),
                ('ls_crop_w', models.TextField(blank=True, null=True)),
                ('ls_crop_y', models.TextField(blank=True, null=True)),
                ('ls_crop_h', models.TextField(blank=True, null=True)),
                ('pt_crop_x', models.TextField(blank=True, null=True)),
                ('pt_crop_w', models.TextField(blank=True, null=True)),
                ('pt_crop_y', models.TextField(blank=True, null=True)),
                ('pt_crop_h', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'card_target_device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('deck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('display_order', models.IntegerField()),
            ],
            options={
                'db_table': 'deck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('media_file_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('path', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'media_file',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaFileType',
            fields=[
                ('media_file_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'media_file_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('orientation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'orientation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('set_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('display_order', models.IntegerField()),
            ],
            options={
                'db_table': 'set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TargetDevice',
            fields=[
                ('target_device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('idiom', models.CharField(max_length=20)),
                ('scale', models.CharField(max_length=2)),
                ('sub_type', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'target_device',
                'managed': False,
            },
        ),
    ]
