# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fc_prod_serv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aspectratio',
            options={'managed': True},
        ),
    ]
